
deployment:
  replicaset: 4
  #pulling from harbor:
  imagename: 192.168.1.179/devops/myapp-a
  imagetag: 1
  pullPolicy: IfNotPresent
  #pulling from git: 
  #imagename: philiprime97/awsviewer
  #imagetag: v1

service:
  type: NodePort
  port: 5001
  targetport: 5001
  nodePort: 31001

ingress:
  enabled: true
  ingressClassName: nginx
  host: awsviewer.com   

aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: "us-east-1"
