apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaset }}
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
          - name: harbor-registry
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.imagename }}:{{ .Values.deployment.imagetag }}
          ports:
            - containerPort: {{ .Values.service.targetport }}
          env:
            {{- if .Values.aws.accessKeyId }}
              - name: AWS_ACCESS_KEY_ID
                value: "{{ .Values.aws.accessKeyId }}"
            {{- end }}

            {{- if .Values.aws.secretAccessKey }}
              - name: AWS_SECRET_ACCESS_KEY
                value: "{{ .Values.aws.secretAccessKey }}"
            {{- end }}

            {{- if .Values.aws.region }}
              - name: AWS_REGION
                value: "{{ .Values.aws.region }}"
              - name: AWS_DEFAULT_REGION
                value: "{{ .Values.aws.region }}"
            {{- end }}
    
