
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /$2 # We strip the prefix before it passes to our backend or our app wont load as it will get route /bears instead /

spec:
 ingressClassName: {{ .Values.ingress.ingressClassName }}
 rules:
  # change the IP below based on the DNS resolution of your LB (under kubectl get svc -n ingress-nginx)
  #host: {{ .Values.ingress.host }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: {{ .Release.Name }}
             port:
                number: {{ .Values.service.port }}
